---
- name: Setting up ALL node
  hosts: master:worker
  become: true
  tasks:
    - name: Change sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
        validate: /usr/sbin/visudo -cf %s

    - name: Update & upgrade apt
      ansible.builtin.apt:
        name: "*"
        state: present
        update_cache: true
        autoremove: true
        autoclean: true
        clean: true
        cache_valid_time: 3600

    - name: Reboot worker
      when: inventory_hostname in groups["worker"]
      ansible.builtin.reboot:
        reboot_timeout: 3600

    - name: Reboot master
      when: inventory_hostname in groups["master"]
      ansible.builtin.reboot:
        reboot_timeout: 3600
