---
- name: Setting up Kubernetes on both Master and Worker nodes
  hosts: master:worker
  vars_files:
    - ../vars/main.yml
  become: true
  tasks:
    - name: Installing Dependencies
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - ca-certificates
        - gnupg
        - runc

    - name: Remove swapfile from /etc/fstab
      ansible.posix.mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      ansible.builtin.command: swapoff -a
      changed_when: ansible_swaptotal_mb >= 0

    - name: Downloading Containerd and CNI Plugin binary
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /home/{{ remote_username }}/
        mode: "0664"
      with_items:
        - https://github.com/containerd/containerd/releases/download/v1.6.8/containerd-1.6.8-linux-amd64.tar.gz
        - https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz

    - name: Unpacking Containerd binary
      ansible.builtin.unarchive:
        src: /home/{{ remote_username }}/containerd-1.6.8-linux-amd64.tar.gz
        dest: /usr/local
        remote_src: true

    - name: Downloading Containerd.service
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        dest: /lib/systemd/system/containerd.service
        mode: "0664"

    - name: Start & Enable Containerd
      ansible.builtin.service:
        name: containerd
        daemon_reload: true
        state: started

    - name: Create CNI Plugin Directory
      ansible.builtin.file:
        path: /opt/cni/bin
        state: directory
        mode: "0644"

    - name: Unpacking CNI Plugin binary
      ansible.builtin.unarchive:
        src: /home/{{ remote_username }}/cni-plugins-linux-amd64-v1.3.0.tgz
        dest: /opt/cni/bin
        remote_src: true

    - name: Adding GPG Key for Kubernetes
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding Repository for Kubernetes
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install Kubernetes Dependencies
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Restart kubelet
      ansible.builtin.service:
        name: kubelet
        daemon_reload: true
        state: restarted

    - name: Initialize the Kubernetes cluster using kubeadm command
      when: inventory_hostname in groups["master"]
      ansible.builtin.command: "sudo kubeadm init \
        --pod-network-cidr=10.244.0.0/16 \
        --apiserver-advertise-address=10.230.0.10 \
        --control-plane-endpoint {{ master_node_public_ip }}:6443"
      register: kubernetes_init
      failed_when:
        - "'cni plugin not initialized' in kubernetes_init.stderr"
      changed_when: false
      timeout: 10000

    - name: Debug - Kubeadm init
      when: inventory_hostname in groups["master"]
      ansible.builtin.debug:
        var: item
      loop:
        - "{{ kubernetes_init.stdout }}"
        - "{{ kubernetes_init.stderr }}"

    - name: Pause for 10 seconds to build Kubernetes
      ansible.builtin.pause:
        seconds: 10

    - name: Create .kube
      ansible.builtin.file:
        path: /home/{{ remote_username }}/.kube
        state: directory
        mode: "0755"

    - name: Copy kubeconfig
      when: inventory_hostname in groups["master"]
      ansible.builtin.copy:
        remote_src: true
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ remote_username }}/.kube/config
        mode: "0755"

    - name: Copying kubeconfig to local
      when: inventory_hostname in groups["master"]
      ansible.builtin.fetch:
        src: "/home/{{ remote_username }}/.kube/config"
        dest: "{{ local_dir }}/.kube/kubeconfig.yaml"
        flat: true

    # This is to join worker nodes using kubeconfig file copied from the master node
    # - name: Copying kubeconfig to worker nodes
    #   when: inventory_hostname in groups["worker"]
    #   ansible.builtin.copy:
    #     src: "{{ local_dir }}/.kube/kubeconfig.yaml"
    #     dest: "/home/{{ remote_username }}/.kube/join.conf"
    #     mode: "0755"

    # - name: Running kubeadm join in worker nodes
    #   when: inventory_hostname in groups["worker"]
    #   ansible.builtin.command: sudo kubeadm join --discovery-file /home/{{ remote_username }}/.kube/join.conf
    #   changed_when: false
    # - - - - - - - - - - - - - - - - - #

    - name: Retrieve Kubernetes join command that is used to join worker node(s)
      become: false
      when: inventory_hostname in groups['master']
      ansible.builtin.command: kubeadm token create --print-join-command --description "[{{ item }}] worker-{{ index }}"
      register: join_command
      changed_when: false
      loop: "{{ worker_node_private_ips }}"
      loop_control:
        index_var: index

    - name: Attach kubeadm join command to a file on Ansible control node
      when: inventory_hostname in groups['master']
      delegate_to: localhost
      ansible.builtin.copy:
        mode: "0777"
        dest: "{{ local_dir }}/devops/ansible/playbook/command/{{ item }}"
        content: "{{ join_command.results[index].stdout }}"
      loop: "{{ worker_node_private_ips }}"
      loop_control:
        index_var: index

    - name: Copy the join-command file created to worker node
      when: inventory_hostname in groups['worker']
      ansible.builtin.copy:
        src: "{{ local_dir }}/devops/ansible/playbook/command/{{ inventory_hostname }}"
        dest: /tmp/kubeadm-join.sh
        mode: "0777"
        remote_src: false

    - name: Join the worker node to cluster
      when: inventory_hostname in groups['worker']
      ansible.builtin.command: sh /tmp/kubeadm-join.sh
      register: join_worker
      changed_when: false
      failed_when:
        - "'cni plugin not initialized' in join_worker.stderr"

    - name: Delete join command files
      when: inventory_hostname in groups["master"]
      delegate_to: localhost
      ansible.builtin.file:
        state: absent
        path: "{{ local_dir }}/devops/ansible/playbook/command/{{ item }}"
        mode: "0777"
      loop: "{{ worker_node_private_ips }}"
      loop_control:
        index_var: index

    - name: Install Flannel pod network
      when: inventory_hostname in groups["master"]
      become: false
      ansible.builtin.command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      changed_when: false
