---
- name: Update Kubeconfig file
  hosts: local
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Adding kubeconfig to local CLI
      become: true
      ansible.builtin.blockinfile:
        path: "/Users/{{ local_username }}/.zshrc"
        # backup: yes
        block: |

          export KUBECONFIG={{ local_dir }}/.kube/kubeconfig.yaml
