---
- name: Adding SSH Key & Update SSH config file to Master Node
  hosts: master
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: Adding Private SSH key
      become: true
      ansible.builtin.copy:
        src: "{{ local_dir }}/devops/ssh/ssh-key"
        dest: "/home/{{ remote_username }}/.ssh/"
        # owner: "{{ remote_username }}"
        # group: "{{ remote_username }}"
        mode: "0744"
    - name: Create SSH config file
      become: true
      ansible.builtin.file:
        state: touch
        path: "/home/{{ remote_username }}/.ssh/config"
        mode: "0644"
    - name: Edit config to add new SSH key
      become: true
      ansible.builtin.blockinfile:
        path: "/home/{{ remote_username }}/.ssh/config"
        # backup: yes
        block: |

          Host {{ item }}
            HostName worker-{{ index }}
            User {{ remote_username }}
            IdentityFile ~/.ssh/ssh-key

      loop: "{{ worker_node_private_ips }}"
      loop_control:
        index_var: index
